-- Route-aware sequence copy (Kelvin's decision 1, 2026-10-06).
--
-- THE PROBLEM. Copy was generated by lead_source, which is a PROVENANCE fact
-- ("a job posting found this company"), and the channel was baked into the
-- prompt that provenance happened to select. So consulting leads got a
-- LinkedIn sequence -- touch_1 written as a "connection request note", touch_2
-- as "sent 3 days after the connection request is accepted" -- while scraper
-- v2 routed them to outbound_email and MKT-O5 EMAILED that text. The copy
-- described a channel it was not delivered on.
--
-- Channel is lead_route. Two columns make that explicit and auditable:
--
--   subject            an email sequence needs one, and MKT-O5 was inventing
--                      "Quick question, {first_name}" at send time for every
--                      lead -- a subject nobody wrote, reviewed or approved.
--                      NULL for the LinkedIn route, which has no subject.
--
--   drafted_for_route  the route the copy was WRITTEN for. A lead's route can
--                      change (an email grade improves, a catch-all becomes
--                      sendable), and without recording this there is no way
--                      to tell that a draft is now for the wrong channel --
--                      it would simply sit in the queue looking fine. MKT-O2
--                      regenerates when this disagrees with the lead's
--                      current lead_route.

ALTER TABLE mse_dm_sequences
    ADD COLUMN IF NOT EXISTS subject text;

ALTER TABLE mse_dm_sequences
    ADD COLUMN IF NOT EXISTS drafted_for_route text
        CHECK (drafted_for_route IS NULL
               OR drafted_for_route = ANY (ARRAY['outbound_email'::text,
                                                 'manual_linkedin'::text]));

COMMENT ON COLUMN mse_dm_sequences.subject IS
    'Email subject line, written and reviewed with the body. NULL on the '
    'manual_linkedin route, which has no subject. Before 2026-10-06 MKT-O5 '
    'invented one at send time, so the subject was the only part of a '
    'prospect-facing email no human ever approved.';

COMMENT ON COLUMN mse_dm_sequences.drafted_for_route IS
    'The lead_route this copy was written for. When it disagrees with the '
    'lead''s current lead_route the draft is for the wrong channel and MKT-O2 '
    'regenerates it.';

-- Backfill: every existing draft was written by the LinkedIn-shaped
-- consulting prompt or the Cloud Decoded email prompt. Marking them by the
-- prompt that produced them (lead_source), not by the lead's current route,
-- so the mismatch this migration exists to surface stays visible rather than
-- being papered over.
UPDATE mse_dm_sequences
   SET drafted_for_route = CASE
         WHEN lead_source = 'cloud_decoded_job_signal' THEN 'outbound_email'
         ELSE 'manual_linkedin'
       END
 WHERE drafted_for_route IS NULL;
